[pytest]
testpaths = tests
filterwarnings =
    ignore:Using default SECRET_KEY - NEVER use in production!:UserWarning
    ignore:ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead:DeprecationWarning
    ignore:Attribute s is deprecated and will be removed in Python 3.14; use value instead:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated and scheduled for removal in a future version.*:DeprecationWarning
